name = "aham"
version = "1.0.0"

description = "Build multilingual Gleam applications"
licences = ["BSL-1.0"]
repository = {type = "github", user = "salif", repo = "aham"}
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
envoy = ">= 1.0.1 and < 2.0.0"
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
